//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPRD.LHD.MessageService
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_GROUPS
    {
        public string UserGroupID { get; set; }
        public Nullable<System.DateTime> JoinTime { get; set; }
        public string GroupID { get; set; }
        public string AccountID { get; set; }
        public Nullable<System.DateTime> QuitTime { get; set; }
        public Nullable<byte> RecordState { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string LastOperator { get; set; }
    }
}
