//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPRD.LHD.SD.MailReceive
{
    using System;
    using System.Collections.Generic;
    
    public partial class URLS
    {
        public string UrlID { get; set; }
        public string UrlPath { get; set; }
        public string NavigatorID { get; set; }
        public string AllowRoles { get; set; }
        public string PageUrl { get; set; }
        public string Title { get; set; }
    }
}
