//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPRD.LHD.MessageService
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOTSImportLogs
    {
        public int ID { get; set; }
        public string FilePath { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string FormatStatus { get; set; }
        public Nullable<System.DateTime> FormatTime { get; set; }
        public string ImportLHDStatus { get; set; }
        public Nullable<System.DateTime> ImportLHDTime { get; set; }
        public string LotNO { get; set; }
        public string Device { get; set; }
        public string Stage { get; set; }
        public string Logs { get; set; }
        public string osatID { get; set; }
        public string Type { get; set; }
    }
}
