//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMSServicesTest.WebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AMSEntity", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AMSEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AMSServicesTest.WebService.AMSRequest[] AMSRequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AMSServicesTest.WebService.AMSRequestActivityFFS[] AMSRequestActivityFFSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AMSServicesTest.WebService.AMSRequestActivityDetail[] AMSRequestActivityDetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AMSServicesTest.WebService.AMSSobjRequestBase[] AMSSobjRequestBaseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public AMSServicesTest.WebService.AMSRequest[] AMSRequest {
            get {
                return this.AMSRequestField;
            }
            set {
                if ((object.ReferenceEquals(this.AMSRequestField, value) != true)) {
                    this.AMSRequestField = value;
                    this.RaisePropertyChanged("AMSRequest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public AMSServicesTest.WebService.AMSRequestActivityFFS[] AMSRequestActivityFFS {
            get {
                return this.AMSRequestActivityFFSField;
            }
            set {
                if ((object.ReferenceEquals(this.AMSRequestActivityFFSField, value) != true)) {
                    this.AMSRequestActivityFFSField = value;
                    this.RaisePropertyChanged("AMSRequestActivityFFS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public AMSServicesTest.WebService.AMSRequestActivityDetail[] AMSRequestActivityDetail {
            get {
                return this.AMSRequestActivityDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.AMSRequestActivityDetailField, value) != true)) {
                    this.AMSRequestActivityDetailField = value;
                    this.RaisePropertyChanged("AMSRequestActivityDetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public AMSServicesTest.WebService.AMSSobjRequestBase[] AMSSobjRequestBase {
            get {
                return this.AMSSobjRequestBaseField;
            }
            set {
                if ((object.ReferenceEquals(this.AMSSobjRequestBaseField, value) != true)) {
                    this.AMSSobjRequestBaseField = value;
                    this.RaisePropertyChanged("AMSSobjRequestBase");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AMSRequest", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AMSRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SysIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IONumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IOSubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IODesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AMSNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InitiatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InsititutionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InsititutionNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JustifiedBusinessSelectionCriteriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        private System.Nullable<System.DateTime> CreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        private System.Nullable<System.DateTime> UpdateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LatestVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RFCActivityField;
        
        private System.DateTime SyncTimeField;
        
        private bool IsActiveField;
        
        private bool IsHandledField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SysId {
            get {
                return this.SysIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SysIdField, value) != true)) {
                    this.SysIdField = value;
                    this.RaisePropertyChanged("SysId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string RequestID {
            get {
                return this.RequestIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestIDField, value) != true)) {
                    this.RequestIDField = value;
                    this.RaisePropertyChanged("RequestID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string IONumber {
            get {
                return this.IONumberField;
            }
            set {
                if ((object.ReferenceEquals(this.IONumberField, value) != true)) {
                    this.IONumberField = value;
                    this.RaisePropertyChanged("IONumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string IOSubject {
            get {
                return this.IOSubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.IOSubjectField, value) != true)) {
                    this.IOSubjectField = value;
                    this.RaisePropertyChanged("IOSubject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string IODes {
            get {
                return this.IODesField;
            }
            set {
                if ((object.ReferenceEquals(this.IODesField, value) != true)) {
                    this.IODesField = value;
                    this.RaisePropertyChanged("IODes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string AMSNumber {
            get {
                return this.AMSNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AMSNumberField, value) != true)) {
                    this.AMSNumberField = value;
                    this.RaisePropertyChanged("AMSNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string TA {
            get {
                return this.TAField;
            }
            set {
                if ((object.ReferenceEquals(this.TAField, value) != true)) {
                    this.TAField = value;
                    this.RaisePropertyChanged("TA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string InitiatedBy {
            get {
                return this.InitiatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.InitiatedByField, value) != true)) {
                    this.InitiatedByField = value;
                    this.RaisePropertyChanged("InitiatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string InsititutionType {
            get {
                return this.InsititutionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.InsititutionTypeField, value) != true)) {
                    this.InsititutionTypeField = value;
                    this.RaisePropertyChanged("InsititutionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string InsititutionName {
            get {
                return this.InsititutionNameField;
            }
            set {
                if ((object.ReferenceEquals(this.InsititutionNameField, value) != true)) {
                    this.InsititutionNameField = value;
                    this.RaisePropertyChanged("InsititutionName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string JustifiedBusinessSelectionCriteria {
            get {
                return this.JustifiedBusinessSelectionCriteriaField;
            }
            set {
                if ((object.ReferenceEquals(this.JustifiedBusinessSelectionCriteriaField, value) != true)) {
                    this.JustifiedBusinessSelectionCriteriaField = value;
                    this.RaisePropertyChanged("JustifiedBusinessSelectionCriteria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public System.Nullable<System.DateTime> CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public System.Nullable<System.DateTime> UpdateTime {
            get {
                return this.UpdateTimeField;
            }
            set {
                if ((this.UpdateTimeField.Equals(value) != true)) {
                    this.UpdateTimeField = value;
                    this.RaisePropertyChanged("UpdateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string UpdatedBy {
            get {
                return this.UpdatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedByField, value) != true)) {
                    this.UpdatedByField = value;
                    this.RaisePropertyChanged("UpdatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string LatestVersion {
            get {
                return this.LatestVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.LatestVersionField, value) != true)) {
                    this.LatestVersionField = value;
                    this.RaisePropertyChanged("LatestVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string RFCActivity {
            get {
                return this.RFCActivityField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCActivityField, value) != true)) {
                    this.RFCActivityField = value;
                    this.RaisePropertyChanged("RFCActivity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public System.DateTime SyncTime {
            get {
                return this.SyncTimeField;
            }
            set {
                if ((this.SyncTimeField.Equals(value) != true)) {
                    this.SyncTimeField = value;
                    this.RaisePropertyChanged("SyncTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=21)]
        public bool IsHandled {
            get {
                return this.IsHandledField;
            }
            set {
                if ((this.IsHandledField.Equals(value) != true)) {
                    this.IsHandledField = value;
                    this.RaisePropertyChanged("IsHandled");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AMSRequestActivityFFS", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AMSRequestActivityFFS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SysIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Activity_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CVPoolIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProviderNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProviderBelongsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProviderLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SelectionCriteriaField;
        
        private System.Nullable<float> Planed_ProvidingTimeField;
        
        private System.Nullable<float> Planed_FeePerTimeField;
        
        private System.Nullable<float> Planed_TotalField;
        
        private System.Nullable<bool> IsBackUpField;
        
        private System.Nullable<float> Actual_ProvidingTimeField;
        
        private System.Nullable<float> Actual_FeePerTimeField;
        
        private System.Nullable<float> Actual_TotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvidingUnitField;
        
        private System.Nullable<bool> AttendedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SAPCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        private System.Nullable<float> ExchangeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaxField;
        
        private System.Nullable<float> ActualPaymentField;
        
        private System.Nullable<System.DateTime> CreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        private System.Nullable<System.DateTime> UpdateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDCardField;
        
        private System.Nullable<float> ParticipatCountField;
        
        private System.Nullable<float> ParticipatAmountSUMField;
        
        private System.Nullable<float> ParticipateAmountLimitField;
        
        private System.Nullable<float> AmountPercentField;
        
        private System.DateTime SyncTimeField;
        
        private bool IsActiveField;
        
        private bool IsHandledField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SysId {
            get {
                return this.SysIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SysIdField, value) != true)) {
                    this.SysIdField = value;
                    this.RaisePropertyChanged("SysId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string RequestID {
            get {
                return this.RequestIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestIDField, value) != true)) {
                    this.RequestIDField = value;
                    this.RaisePropertyChanged("RequestID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Activity_ID {
            get {
                return this.Activity_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.Activity_IDField, value) != true)) {
                    this.Activity_IDField = value;
                    this.RaisePropertyChanged("Activity_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CVPoolID {
            get {
                return this.CVPoolIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CVPoolIDField, value) != true)) {
                    this.CVPoolIDField = value;
                    this.RaisePropertyChanged("CVPoolID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ProviderName {
            get {
                return this.ProviderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProviderNameField, value) != true)) {
                    this.ProviderNameField = value;
                    this.RaisePropertyChanged("ProviderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ProviderBelongs {
            get {
                return this.ProviderBelongsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProviderBelongsField, value) != true)) {
                    this.ProviderBelongsField = value;
                    this.RaisePropertyChanged("ProviderBelongs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ProviderLevel {
            get {
                return this.ProviderLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.ProviderLevelField, value) != true)) {
                    this.ProviderLevelField = value;
                    this.RaisePropertyChanged("ProviderLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string SelectionCriteria {
            get {
                return this.SelectionCriteriaField;
            }
            set {
                if ((object.ReferenceEquals(this.SelectionCriteriaField, value) != true)) {
                    this.SelectionCriteriaField = value;
                    this.RaisePropertyChanged("SelectionCriteria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.Nullable<float> Planed_ProvidingTime {
            get {
                return this.Planed_ProvidingTimeField;
            }
            set {
                if ((this.Planed_ProvidingTimeField.Equals(value) != true)) {
                    this.Planed_ProvidingTimeField = value;
                    this.RaisePropertyChanged("Planed_ProvidingTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.Nullable<float> Planed_FeePerTime {
            get {
                return this.Planed_FeePerTimeField;
            }
            set {
                if ((this.Planed_FeePerTimeField.Equals(value) != true)) {
                    this.Planed_FeePerTimeField = value;
                    this.RaisePropertyChanged("Planed_FeePerTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public System.Nullable<float> Planed_Total {
            get {
                return this.Planed_TotalField;
            }
            set {
                if ((this.Planed_TotalField.Equals(value) != true)) {
                    this.Planed_TotalField = value;
                    this.RaisePropertyChanged("Planed_Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public System.Nullable<bool> IsBackUp {
            get {
                return this.IsBackUpField;
            }
            set {
                if ((this.IsBackUpField.Equals(value) != true)) {
                    this.IsBackUpField = value;
                    this.RaisePropertyChanged("IsBackUp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public System.Nullable<float> Actual_ProvidingTime {
            get {
                return this.Actual_ProvidingTimeField;
            }
            set {
                if ((this.Actual_ProvidingTimeField.Equals(value) != true)) {
                    this.Actual_ProvidingTimeField = value;
                    this.RaisePropertyChanged("Actual_ProvidingTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public System.Nullable<float> Actual_FeePerTime {
            get {
                return this.Actual_FeePerTimeField;
            }
            set {
                if ((this.Actual_FeePerTimeField.Equals(value) != true)) {
                    this.Actual_FeePerTimeField = value;
                    this.RaisePropertyChanged("Actual_FeePerTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public System.Nullable<float> Actual_Total {
            get {
                return this.Actual_TotalField;
            }
            set {
                if ((this.Actual_TotalField.Equals(value) != true)) {
                    this.Actual_TotalField = value;
                    this.RaisePropertyChanged("Actual_Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string ProvidingUnit {
            get {
                return this.ProvidingUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvidingUnitField, value) != true)) {
                    this.ProvidingUnitField = value;
                    this.RaisePropertyChanged("ProvidingUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public System.Nullable<bool> Attended {
            get {
                return this.AttendedField;
            }
            set {
                if ((this.AttendedField.Equals(value) != true)) {
                    this.AttendedField = value;
                    this.RaisePropertyChanged("Attended");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string SAPCode {
            get {
                return this.SAPCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SAPCodeField, value) != true)) {
                    this.SAPCodeField = value;
                    this.RaisePropertyChanged("SAPCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=21)]
        public System.Nullable<float> Exchange {
            get {
                return this.ExchangeField;
            }
            set {
                if ((this.ExchangeField.Equals(value) != true)) {
                    this.ExchangeField = value;
                    this.RaisePropertyChanged("Exchange");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string Tax {
            get {
                return this.TaxField;
            }
            set {
                if ((object.ReferenceEquals(this.TaxField, value) != true)) {
                    this.TaxField = value;
                    this.RaisePropertyChanged("Tax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=23)]
        public System.Nullable<float> ActualPayment {
            get {
                return this.ActualPaymentField;
            }
            set {
                if ((this.ActualPaymentField.Equals(value) != true)) {
                    this.ActualPaymentField = value;
                    this.RaisePropertyChanged("ActualPayment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=24)]
        public System.Nullable<System.DateTime> CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=26)]
        public System.Nullable<System.DateTime> UpdateTime {
            get {
                return this.UpdateTimeField;
            }
            set {
                if ((this.UpdateTimeField.Equals(value) != true)) {
                    this.UpdateTimeField = value;
                    this.RaisePropertyChanged("UpdateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string UpdatedBy {
            get {
                return this.UpdatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedByField, value) != true)) {
                    this.UpdatedByField = value;
                    this.RaisePropertyChanged("UpdatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string IDCard {
            get {
                return this.IDCardField;
            }
            set {
                if ((object.ReferenceEquals(this.IDCardField, value) != true)) {
                    this.IDCardField = value;
                    this.RaisePropertyChanged("IDCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=29)]
        public System.Nullable<float> ParticipatCount {
            get {
                return this.ParticipatCountField;
            }
            set {
                if ((this.ParticipatCountField.Equals(value) != true)) {
                    this.ParticipatCountField = value;
                    this.RaisePropertyChanged("ParticipatCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=30)]
        public System.Nullable<float> ParticipatAmountSUM {
            get {
                return this.ParticipatAmountSUMField;
            }
            set {
                if ((this.ParticipatAmountSUMField.Equals(value) != true)) {
                    this.ParticipatAmountSUMField = value;
                    this.RaisePropertyChanged("ParticipatAmountSUM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=31)]
        public System.Nullable<float> ParticipateAmountLimit {
            get {
                return this.ParticipateAmountLimitField;
            }
            set {
                if ((this.ParticipateAmountLimitField.Equals(value) != true)) {
                    this.ParticipateAmountLimitField = value;
                    this.RaisePropertyChanged("ParticipateAmountLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=32)]
        public System.Nullable<float> AmountPercent {
            get {
                return this.AmountPercentField;
            }
            set {
                if ((this.AmountPercentField.Equals(value) != true)) {
                    this.AmountPercentField = value;
                    this.RaisePropertyChanged("AmountPercent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=33)]
        public System.DateTime SyncTime {
            get {
                return this.SyncTimeField;
            }
            set {
                if ((this.SyncTimeField.Equals(value) != true)) {
                    this.SyncTimeField = value;
                    this.RaisePropertyChanged("SyncTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=34)]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=35)]
        public bool IsHandled {
            get {
                return this.IsHandledField;
            }
            set {
                if ((this.IsHandledField.Equals(value) != true)) {
                    this.IsHandledField = value;
                    this.RaisePropertyChanged("IsHandled");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AMSRequestActivityDetail", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AMSRequestActivityDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SysIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestIDField;
        
        private System.Nullable<bool> HasServiceProviderField;
        
        private System.Nullable<bool> ProductRelatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentAndProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GLAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CostCenterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Sub_AMSNumberField;
        
        private System.Nullable<System.DateTime> BeginDateField;
        
        private System.Nullable<System.DateTime> EndDateField;
        
        private System.Nullable<float> Planning_Participant_InternalQuantityField;
        
        private System.Nullable<float> Planning_Participant_ExternalQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Planning_CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Planning_CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Planning_LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Planning_DescriptionField;
        
        private System.Nullable<System.DateTime> Actual_BeginDateField;
        
        private System.Nullable<System.DateTime> Actual_EndDateField;
        
        private System.Nullable<float> Actual_Participant_InternalQuantityField;
        
        private System.Nullable<float> Actual_Participant_ExternalQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Actual_CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Actual_LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        private System.Nullable<float> ExpenseSubTotalField;
        
        private System.Nullable<float> FFSSubTotalField;
        
        private System.Nullable<float> TotalField;
        
        private bool DefaultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        private System.Nullable<System.DateTime> CreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        private System.Nullable<System.DateTime> UpdateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MonitorStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FreezeStatusField;
        
        private System.DateTime SyncTimeField;
        
        private bool IsActiveField;
        
        private bool IsHandledField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SysId {
            get {
                return this.SysIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SysIdField, value) != true)) {
                    this.SysIdField = value;
                    this.RaisePropertyChanged("SysId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string RequestID {
            get {
                return this.RequestIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestIDField, value) != true)) {
                    this.RequestIDField = value;
                    this.RaisePropertyChanged("RequestID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<bool> HasServiceProvider {
            get {
                return this.HasServiceProviderField;
            }
            set {
                if ((this.HasServiceProviderField.Equals(value) != true)) {
                    this.HasServiceProviderField = value;
                    this.RaisePropertyChanged("HasServiceProvider");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<bool> ProductRelated {
            get {
                return this.ProductRelatedField;
            }
            set {
                if ((this.ProductRelatedField.Equals(value) != true)) {
                    this.ProductRelatedField = value;
                    this.RaisePropertyChanged("ProductRelated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string DepartmentAndProduct {
            get {
                return this.DepartmentAndProductField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentAndProductField, value) != true)) {
                    this.DepartmentAndProductField = value;
                    this.RaisePropertyChanged("DepartmentAndProduct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string GLAccount {
            get {
                return this.GLAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.GLAccountField, value) != true)) {
                    this.GLAccountField = value;
                    this.RaisePropertyChanged("GLAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string CostCenter {
            get {
                return this.CostCenterField;
            }
            set {
                if ((object.ReferenceEquals(this.CostCenterField, value) != true)) {
                    this.CostCenterField = value;
                    this.RaisePropertyChanged("CostCenter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Sub_AMSNumber {
            get {
                return this.Sub_AMSNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.Sub_AMSNumberField, value) != true)) {
                    this.Sub_AMSNumberField = value;
                    this.RaisePropertyChanged("Sub_AMSNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.Nullable<System.DateTime> BeginDate {
            get {
                return this.BeginDateField;
            }
            set {
                if ((this.BeginDateField.Equals(value) != true)) {
                    this.BeginDateField = value;
                    this.RaisePropertyChanged("BeginDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.Nullable<System.DateTime> EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.Nullable<float> Planning_Participant_InternalQuantity {
            get {
                return this.Planning_Participant_InternalQuantityField;
            }
            set {
                if ((this.Planning_Participant_InternalQuantityField.Equals(value) != true)) {
                    this.Planning_Participant_InternalQuantityField = value;
                    this.RaisePropertyChanged("Planning_Participant_InternalQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public System.Nullable<float> Planning_Participant_ExternalQuantity {
            get {
                return this.Planning_Participant_ExternalQuantityField;
            }
            set {
                if ((this.Planning_Participant_ExternalQuantityField.Equals(value) != true)) {
                    this.Planning_Participant_ExternalQuantityField = value;
                    this.RaisePropertyChanged("Planning_Participant_ExternalQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Planning_Country {
            get {
                return this.Planning_CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.Planning_CountryField, value) != true)) {
                    this.Planning_CountryField = value;
                    this.RaisePropertyChanged("Planning_Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string Planning_City {
            get {
                return this.Planning_CityField;
            }
            set {
                if ((object.ReferenceEquals(this.Planning_CityField, value) != true)) {
                    this.Planning_CityField = value;
                    this.RaisePropertyChanged("Planning_City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string Planning_Location {
            get {
                return this.Planning_LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.Planning_LocationField, value) != true)) {
                    this.Planning_LocationField = value;
                    this.RaisePropertyChanged("Planning_Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string Planning_Description {
            get {
                return this.Planning_DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.Planning_DescriptionField, value) != true)) {
                    this.Planning_DescriptionField = value;
                    this.RaisePropertyChanged("Planning_Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public System.Nullable<System.DateTime> Actual_BeginDate {
            get {
                return this.Actual_BeginDateField;
            }
            set {
                if ((this.Actual_BeginDateField.Equals(value) != true)) {
                    this.Actual_BeginDateField = value;
                    this.RaisePropertyChanged("Actual_BeginDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public System.Nullable<System.DateTime> Actual_EndDate {
            get {
                return this.Actual_EndDateField;
            }
            set {
                if ((this.Actual_EndDateField.Equals(value) != true)) {
                    this.Actual_EndDateField = value;
                    this.RaisePropertyChanged("Actual_EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public System.Nullable<float> Actual_Participant_InternalQuantity {
            get {
                return this.Actual_Participant_InternalQuantityField;
            }
            set {
                if ((this.Actual_Participant_InternalQuantityField.Equals(value) != true)) {
                    this.Actual_Participant_InternalQuantityField = value;
                    this.RaisePropertyChanged("Actual_Participant_InternalQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public System.Nullable<float> Actual_Participant_ExternalQuantity {
            get {
                return this.Actual_Participant_ExternalQuantityField;
            }
            set {
                if ((this.Actual_Participant_ExternalQuantityField.Equals(value) != true)) {
                    this.Actual_Participant_ExternalQuantityField = value;
                    this.RaisePropertyChanged("Actual_Participant_ExternalQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string Actual_City {
            get {
                return this.Actual_CityField;
            }
            set {
                if ((object.ReferenceEquals(this.Actual_CityField, value) != true)) {
                    this.Actual_CityField = value;
                    this.RaisePropertyChanged("Actual_City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string Actual_Location {
            get {
                return this.Actual_LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.Actual_LocationField, value) != true)) {
                    this.Actual_LocationField = value;
                    this.RaisePropertyChanged("Actual_Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=24)]
        public System.Nullable<float> ExpenseSubTotal {
            get {
                return this.ExpenseSubTotalField;
            }
            set {
                if ((this.ExpenseSubTotalField.Equals(value) != true)) {
                    this.ExpenseSubTotalField = value;
                    this.RaisePropertyChanged("ExpenseSubTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=25)]
        public System.Nullable<float> FFSSubTotal {
            get {
                return this.FFSSubTotalField;
            }
            set {
                if ((this.FFSSubTotalField.Equals(value) != true)) {
                    this.FFSSubTotalField = value;
                    this.RaisePropertyChanged("FFSSubTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=26)]
        public System.Nullable<float> Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=27)]
        public bool Default {
            get {
                return this.DefaultField;
            }
            set {
                if ((this.DefaultField.Equals(value) != true)) {
                    this.DefaultField = value;
                    this.RaisePropertyChanged("Default");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=29)]
        public System.Nullable<System.DateTime> CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=30)]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=31)]
        public System.Nullable<System.DateTime> UpdateTime {
            get {
                return this.UpdateTimeField;
            }
            set {
                if ((this.UpdateTimeField.Equals(value) != true)) {
                    this.UpdateTimeField = value;
                    this.RaisePropertyChanged("UpdateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=32)]
        public string UpdatedBy {
            get {
                return this.UpdatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedByField, value) != true)) {
                    this.UpdatedByField = value;
                    this.RaisePropertyChanged("UpdatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=33)]
        public string MonitorStatus {
            get {
                return this.MonitorStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.MonitorStatusField, value) != true)) {
                    this.MonitorStatusField = value;
                    this.RaisePropertyChanged("MonitorStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=34)]
        public string FreezeStatus {
            get {
                return this.FreezeStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.FreezeStatusField, value) != true)) {
                    this.FreezeStatusField = value;
                    this.RaisePropertyChanged("FreezeStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=35)]
        public System.DateTime SyncTime {
            get {
                return this.SyncTimeField;
            }
            set {
                if ((this.SyncTimeField.Equals(value) != true)) {
                    this.SyncTimeField = value;
                    this.RaisePropertyChanged("SyncTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=36)]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=37)]
        public bool IsHandled {
            get {
                return this.IsHandledField;
            }
            set {
                if ((this.IsHandledField.Equals(value) != true)) {
                    this.IsHandledField = value;
                    this.RaisePropertyChanged("IsHandled");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AMSSobjRequestBase", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AMSSobjRequestBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SysIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestSubjectField;
        
        private System.Nullable<System.DateTime> CreatedTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicantWWIDField;
        
        private System.Nullable<bool> SMSNotificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SMSNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        private System.Nullable<System.DateTime> DueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatorWWIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProcessTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObjectIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupervisorWWIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupervisorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicantNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicantAdAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicantPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicantEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatorAdAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupervisorAdAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApprovedDateField;
        
        private System.DateTime LatestUpdateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProcessNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtendedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicantTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        private System.DateTime SyncTimeField;
        
        private bool IsActiveField;
        
        private bool IsHandledField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SysId {
            get {
                return this.SysIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SysIdField, value) != true)) {
                    this.SysIdField = value;
                    this.RaisePropertyChanged("SysId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string RequestSubject {
            get {
                return this.RequestSubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestSubjectField, value) != true)) {
                    this.RequestSubjectField = value;
                    this.RaisePropertyChanged("RequestSubject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<System.DateTime> CreatedTime {
            get {
                return this.CreatedTimeField;
            }
            set {
                if ((this.CreatedTimeField.Equals(value) != true)) {
                    this.CreatedTimeField = value;
                    this.RaisePropertyChanged("CreatedTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string RequestStatus {
            get {
                return this.RequestStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestStatusField, value) != true)) {
                    this.RequestStatusField = value;
                    this.RaisePropertyChanged("RequestStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ApplicantWWID {
            get {
                return this.ApplicantWWIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicantWWIDField, value) != true)) {
                    this.ApplicantWWIDField = value;
                    this.RaisePropertyChanged("ApplicantWWID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<bool> SMSNotification {
            get {
                return this.SMSNotificationField;
            }
            set {
                if ((this.SMSNotificationField.Equals(value) != true)) {
                    this.SMSNotificationField = value;
                    this.RaisePropertyChanged("SMSNotification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string SMSNumber {
            get {
                return this.SMSNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SMSNumberField, value) != true)) {
                    this.SMSNumberField = value;
                    this.RaisePropertyChanged("SMSNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Department {
            get {
                return this.DepartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentField, value) != true)) {
                    this.DepartmentField = value;
                    this.RaisePropertyChanged("Department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.Nullable<System.DateTime> DueDate {
            get {
                return this.DueDateField;
            }
            set {
                if ((this.DueDateField.Equals(value) != true)) {
                    this.DueDateField = value;
                    this.RaisePropertyChanged("DueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string CreatorWWID {
            get {
                return this.CreatorWWIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatorWWIDField, value) != true)) {
                    this.CreatorWWIDField = value;
                    this.RaisePropertyChanged("CreatorWWID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string ProcessType {
            get {
                return this.ProcessTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcessTypeField, value) != true)) {
                    this.ProcessTypeField = value;
                    this.RaisePropertyChanged("ProcessType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string ObjectID {
            get {
                return this.ObjectIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectIDField, value) != true)) {
                    this.ObjectIDField = value;
                    this.RaisePropertyChanged("ObjectID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string SupervisorWWID {
            get {
                return this.SupervisorWWIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SupervisorWWIDField, value) != true)) {
                    this.SupervisorWWIDField = value;
                    this.RaisePropertyChanged("SupervisorWWID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string CreatorName {
            get {
                return this.CreatorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatorNameField, value) != true)) {
                    this.CreatorNameField = value;
                    this.RaisePropertyChanged("CreatorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string SupervisorName {
            get {
                return this.SupervisorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SupervisorNameField, value) != true)) {
                    this.SupervisorNameField = value;
                    this.RaisePropertyChanged("SupervisorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string ApplicantName {
            get {
                return this.ApplicantNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicantNameField, value) != true)) {
                    this.ApplicantNameField = value;
                    this.RaisePropertyChanged("ApplicantName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string ApplicantAdAccount {
            get {
                return this.ApplicantAdAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicantAdAccountField, value) != true)) {
                    this.ApplicantAdAccountField = value;
                    this.RaisePropertyChanged("ApplicantAdAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string ApplicantPhone {
            get {
                return this.ApplicantPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicantPhoneField, value) != true)) {
                    this.ApplicantPhoneField = value;
                    this.RaisePropertyChanged("ApplicantPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string ApplicantEmail {
            get {
                return this.ApplicantEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicantEmailField, value) != true)) {
                    this.ApplicantEmailField = value;
                    this.RaisePropertyChanged("ApplicantEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string CreatorAdAccount {
            get {
                return this.CreatorAdAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatorAdAccountField, value) != true)) {
                    this.CreatorAdAccountField = value;
                    this.RaisePropertyChanged("CreatorAdAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string SupervisorAdAccount {
            get {
                return this.SupervisorAdAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.SupervisorAdAccountField, value) != true)) {
                    this.SupervisorAdAccountField = value;
                    this.RaisePropertyChanged("SupervisorAdAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string CompanyCode {
            get {
                return this.CompanyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyCodeField, value) != true)) {
                    this.CompanyCodeField = value;
                    this.RaisePropertyChanged("CompanyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string ApprovedDate {
            get {
                return this.ApprovedDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ApprovedDateField, value) != true)) {
                    this.ApprovedDateField = value;
                    this.RaisePropertyChanged("ApprovedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=24)]
        public System.DateTime LatestUpdateTime {
            get {
                return this.LatestUpdateTimeField;
            }
            set {
                if ((this.LatestUpdateTimeField.Equals(value) != true)) {
                    this.LatestUpdateTimeField = value;
                    this.RaisePropertyChanged("LatestUpdateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string ProcessName {
            get {
                return this.ProcessNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcessNameField, value) != true)) {
                    this.ProcessNameField = value;
                    this.RaisePropertyChanged("ProcessName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string Extended {
            get {
                return this.ExtendedField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtendedField, value) != true)) {
                    this.ExtendedField = value;
                    this.RaisePropertyChanged("Extended");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string ApplicantTitle {
            get {
                return this.ApplicantTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicantTitleField, value) != true)) {
                    this.ApplicantTitleField = value;
                    this.RaisePropertyChanged("ApplicantTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=29)]
        public System.DateTime SyncTime {
            get {
                return this.SyncTimeField;
            }
            set {
                if ((this.SyncTimeField.Equals(value) != true)) {
                    this.SyncTimeField = value;
                    this.RaisePropertyChanged("SyncTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=30)]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=31)]
        public bool IsHandled {
            get {
                return this.IsHandledField;
            }
            set {
                if ((this.IsHandledField.Equals(value) != true)) {
                    this.IsHandledField = value;
                    this.RaisePropertyChanged("IsHandled");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebService.MeetingAMSSoap")]
    public interface MeetingAMSSoap {
        
        // CODEGEN: Generating message contract since element name entity from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AMSInfomation", ReplyAction="*")]
        AMSServicesTest.WebService.AMSInfomationResponse AMSInfomation(AMSServicesTest.WebService.AMSInfomationRequest request);
        
        // CODEGEN: Generating message contract since element name data from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AMSInfomationNew", ReplyAction="*")]
        AMSServicesTest.WebService.AMSInfomationNewResponse AMSInfomationNew(AMSServicesTest.WebService.AMSInfomationNewRequest request);
        
        // CODEGEN: Generating message contract since element name TestResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Test", ReplyAction="*")]
        AMSServicesTest.WebService.TestResponse Test(AMSServicesTest.WebService.TestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AMSInfomationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AMSInfomation", Namespace="http://tempuri.org/", Order=0)]
        public AMSServicesTest.WebService.AMSInfomationRequestBody Body;
        
        public AMSInfomationRequest() {
        }
        
        public AMSInfomationRequest(AMSServicesTest.WebService.AMSInfomationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AMSInfomationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AMSServicesTest.WebService.AMSEntity entity;
        
        public AMSInfomationRequestBody() {
        }
        
        public AMSInfomationRequestBody(AMSServicesTest.WebService.AMSEntity entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AMSInfomationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AMSInfomationResponse", Namespace="http://tempuri.org/", Order=0)]
        public AMSServicesTest.WebService.AMSInfomationResponseBody Body;
        
        public AMSInfomationResponse() {
        }
        
        public AMSInfomationResponse(AMSServicesTest.WebService.AMSInfomationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AMSInfomationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AMSInfomationResult;
        
        public AMSInfomationResponseBody() {
        }
        
        public AMSInfomationResponseBody(string AMSInfomationResult) {
            this.AMSInfomationResult = AMSInfomationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AMSInfomationNewRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AMSInfomationNew", Namespace="http://tempuri.org/", Order=0)]
        public AMSServicesTest.WebService.AMSInfomationNewRequestBody Body;
        
        public AMSInfomationNewRequest() {
        }
        
        public AMSInfomationNewRequest(AMSServicesTest.WebService.AMSInfomationNewRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AMSInfomationNewRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string data;
        
        public AMSInfomationNewRequestBody() {
        }
        
        public AMSInfomationNewRequestBody(string data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AMSInfomationNewResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AMSInfomationNewResponse", Namespace="http://tempuri.org/", Order=0)]
        public AMSServicesTest.WebService.AMSInfomationNewResponseBody Body;
        
        public AMSInfomationNewResponse() {
        }
        
        public AMSInfomationNewResponse(AMSServicesTest.WebService.AMSInfomationNewResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AMSInfomationNewResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AMSInfomationNewResult;
        
        public AMSInfomationNewResponseBody() {
        }
        
        public AMSInfomationNewResponseBody(string AMSInfomationNewResult) {
            this.AMSInfomationNewResult = AMSInfomationNewResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Test", Namespace="http://tempuri.org/", Order=0)]
        public AMSServicesTest.WebService.TestRequestBody Body;
        
        public TestRequest() {
        }
        
        public TestRequest(AMSServicesTest.WebService.TestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TestRequestBody {
        
        public TestRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestResponse", Namespace="http://tempuri.org/", Order=0)]
        public AMSServicesTest.WebService.TestResponseBody Body;
        
        public TestResponse() {
        }
        
        public TestResponse(AMSServicesTest.WebService.TestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestResult;
        
        public TestResponseBody() {
        }
        
        public TestResponseBody(string TestResult) {
            this.TestResult = TestResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MeetingAMSSoapChannel : AMSServicesTest.WebService.MeetingAMSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MeetingAMSSoapClient : System.ServiceModel.ClientBase<AMSServicesTest.WebService.MeetingAMSSoap>, AMSServicesTest.WebService.MeetingAMSSoap {
        
        public MeetingAMSSoapClient() {
        }
        
        public MeetingAMSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MeetingAMSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MeetingAMSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MeetingAMSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AMSServicesTest.WebService.AMSInfomationResponse AMSServicesTest.WebService.MeetingAMSSoap.AMSInfomation(AMSServicesTest.WebService.AMSInfomationRequest request) {
            return base.Channel.AMSInfomation(request);
        }
        
        public string AMSInfomation(AMSServicesTest.WebService.AMSEntity entity) {
            AMSServicesTest.WebService.AMSInfomationRequest inValue = new AMSServicesTest.WebService.AMSInfomationRequest();
            inValue.Body = new AMSServicesTest.WebService.AMSInfomationRequestBody();
            inValue.Body.entity = entity;
            AMSServicesTest.WebService.AMSInfomationResponse retVal = ((AMSServicesTest.WebService.MeetingAMSSoap)(this)).AMSInfomation(inValue);
            return retVal.Body.AMSInfomationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AMSServicesTest.WebService.AMSInfomationNewResponse AMSServicesTest.WebService.MeetingAMSSoap.AMSInfomationNew(AMSServicesTest.WebService.AMSInfomationNewRequest request) {
            return base.Channel.AMSInfomationNew(request);
        }
        
        public string AMSInfomationNew(string data) {
            AMSServicesTest.WebService.AMSInfomationNewRequest inValue = new AMSServicesTest.WebService.AMSInfomationNewRequest();
            inValue.Body = new AMSServicesTest.WebService.AMSInfomationNewRequestBody();
            inValue.Body.data = data;
            AMSServicesTest.WebService.AMSInfomationNewResponse retVal = ((AMSServicesTest.WebService.MeetingAMSSoap)(this)).AMSInfomationNew(inValue);
            return retVal.Body.AMSInfomationNewResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AMSServicesTest.WebService.TestResponse AMSServicesTest.WebService.MeetingAMSSoap.Test(AMSServicesTest.WebService.TestRequest request) {
            return base.Channel.Test(request);
        }
        
        public string Test() {
            AMSServicesTest.WebService.TestRequest inValue = new AMSServicesTest.WebService.TestRequest();
            inValue.Body = new AMSServicesTest.WebService.TestRequestBody();
            AMSServicesTest.WebService.TestResponse retVal = ((AMSServicesTest.WebService.MeetingAMSSoap)(this)).Test(inValue);
            return retVal.Body.TestResult;
        }
    }
}
