//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPRD.LHD.SD.MailReceive
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILE_HITS
    {
        public string HitID { get; set; }
        public Nullable<System.DateTime> HitTime { get; set; }
        public string FileID { get; set; }
        public string SessionID { get; set; }
        public string ClientID { get; set; }
        public string HitType { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateStamp { get; set; }
    }
}
