//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPRD.LHD.MessageService
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOTSImportSDLogs
    {
        public int ID { get; set; }
        public string OSAT { get; set; }
        public string Device { get; set; }
        public string LotNO { get; set; }
        public string Stage { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string LHDFormatStatus { get; set; }
        public string LHDImportStatus { get; set; }
    }
}
