//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPRD.LHD.MessageService
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOTS
    {
        public string ID { get; set; }
        public string LotID { get; set; }
        public string VenderID { get; set; }
        public string AutoJudgeResult { get; set; }
        public string HoldReason { get; set; }
        public Nullable<bool> ManualHold { get; set; }
        public Nullable<byte> QADispose { get; set; }
        public Nullable<byte> PEDispose { get; set; }
        public Nullable<byte> SPRDDecision { get; set; }
        public string DeviceCode { get; set; }
        public string DeviceName { get; set; }
        public string LotType { get; set; }
        public string LotNO { get; set; }
        public string SubconLot { get; set; }
        public string TestProgram { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public string Die1LotNO { get; set; }
        public string Die1CP { get; set; }
        public string Die2LotNO { get; set; }
        public string Die2CP { get; set; }
        public string Die3LotNO { get; set; }
        public string Die3CP { get; set; }
        public string Die4LotNO { get; set; }
        public string Die4CP { get; set; }
        public Nullable<int> QtyIn { get; set; }
        public Nullable<double> Yield { get; set; }
        public string OSRate { get; set; }
        public Nullable<int> Loss { get; set; }
        public Nullable<int> Damage { get; set; }
        public Nullable<int> Bin1 { get; set; }
        public Nullable<int> Bin2 { get; set; }
        public Nullable<int> Bin3 { get; set; }
        public Nullable<int> Bin4 { get; set; }
        public Nullable<int> Bin5 { get; set; }
        public Nullable<int> Bin6 { get; set; }
        public Nullable<int> Bin7 { get; set; }
        public Nullable<int> RetestTimes { get; set; }
        public string TesterID { get; set; }
        public string Platforms { get; set; }
        public string LBNO { get; set; }
        public Nullable<int> Version { get; set; }
        public string OperatorID { get; set; }
        public Nullable<System.DateTime> OperateTime { get; set; }
        public string PreviousRecordID { get; set; }
        public Nullable<bool> VenderConfirmed { get; set; }
        public Nullable<byte> RecordState { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string LastOperator { get; set; }
        public string Status { get; set; }
        public string VenderJudgeResult { get; set; }
        public string QADisposeText { get; set; }
        public string PEDisposeText { get; set; }
        public string SPRDDecisionText { get; set; }
        public string OperatorName { get; set; }
        public Nullable<int> VersionID { get; set; }
        public string RecordType { get; set; }
        public string OperateType { get; set; }
        public Nullable<int> Bin8 { get; set; }
        public Nullable<int> Bin9 { get; set; }
        public Nullable<int> Bin10 { get; set; }
        public Nullable<bool> OtherBinDispose { get; set; }
        public Nullable<int> LastDecision { get; set; }
        public Nullable<int> SDStates { get; set; }
        public Nullable<bool> OtherBinDisposeConfirmed { get; set; }
        public Nullable<System.DateTime> OtherBinDisposeConfirmTime { get; set; }
        public Nullable<System.DateTime> QADisposeTime { get; set; }
        public Nullable<System.DateTime> PEDisposeTime { get; set; }
        public Nullable<System.DateTime> VenderConfirmTime { get; set; }
        public string LotJudgementMessage { get; set; }
        public string Stage { get; set; }
        public string CustomerLotId { get; set; }
        public string Url { get; set; }
        public Nullable<int> QtyOut { get; set; }
        public Nullable<int> totalCount { get; set; }
        public Nullable<int> passCount { get; set; }
        public string ReasonStepFail { get; set; }
        public string ReasonStepWarn { get; set; }
        public string ReasonSBLFail { get; set; }
        public string ReasonUntestedFail { get; set; }
        public string ReasonStepOrderFail { get; set; }
    }
}
