//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMSServicesTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SpreadtrumLHDEntities : DbContext
    {
        public SpreadtrumLHDEntities()
            : base("name=SpreadtrumLHDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<COMMENTS> COMMENTS { get; set; }
        public DbSet<EMAILS> EMAILS { get; set; }
        public DbSet<FILES> FILES { get; set; }
        public DbSet<GROUPS> GROUPS { get; set; }
        public DbSet<LOT_STATUS> LOT_STATUS { get; set; }
        public DbSet<LOT_STATUS_LIST> LOT_STATUS_LIST { get; set; }
        public DbSet<LOTS> LOTS { get; set; }
        public DbSet<LOTSImportLogs> LOTSImportLogs { get; set; }
        public DbSet<NOTIFICATIONS> NOTIFICATIONS { get; set; }
        public DbSet<SILICONDASH_INTEGRATION> SILICONDASH_INTEGRATION { get; set; }
        public DbSet<SILICONDASH_OSAT_CONFIGURATIONS> SILICONDASH_OSAT_CONFIGURATIONS { get; set; }
        public DbSet<SW_BIN> SW_BIN { get; set; }
        public DbSet<URLS> URLS { get; set; }
        public DbSet<USER_GROUPS> USER_GROUPS { get; set; }
        public DbSet<VENDORS> VENDORS { get; set; }
        public DbSet<FILE_HITS> FILE_HITS { get; set; }
        public DbSet<USERS> USERS { get; set; }
    }
}
