//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMSServicesTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class SILICONDASH_INTEGRATION
    {
        public System.Guid ID { get; set; }
        public string MessageId { get; set; }
        public string MessageContent { get; set; }
        public byte[] CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<System.Guid> LastOperator { get; set; }
    }
}
