//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPRD.LHD.SD.MailReceive
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOT_STATUS_LIST
    {
        public string StatusID { get; set; }
        public Nullable<int> QADispose { get; set; }
        public Nullable<int> PEDispose { get; set; }
        public Nullable<bool> OtherBinDispose { get; set; }
        public Nullable<int> SPRDDecision { get; set; }
        public Nullable<bool> VenderConfirmed { get; set; }
        public Nullable<bool> OtherBinDisposeConfirmed { get; set; }
        public string Status { get; set; }
    }
}
