//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPRD.LHD.MessageService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SILICONDASH_OSAT_CONFIGURATIONS
    {
        public string ConfigurationID { get; set; }
        public string OSATID { get; set; }
        public string URI { get; set; }
        public string LoginID { get; set; }
        public string LoginPWD { get; set; }
        public string InboundChannel { get; set; }
        public string OutboundChannel { get; set; }
        public string MessageInDirectory { get; set; }
        public string MessageOutDirectory { get; set; }
        public Nullable<int> States { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
