//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPRD.LHD.MessageService
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAILS
    {
        public string EmailID { get; set; }
        public string Sender { get; set; }
        public string Cc { get; set; }
        public string Recipients { get; set; }
        public string Subject { get; set; }
        public Nullable<int> HtmlFormat { get; set; }
        public string Body { get; set; }
        public Nullable<int> Priority { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> NextTryTime { get; set; }
        public Nullable<int> TryTime { get; set; }
        public string AccountIDs { get; set; }
    }
}
