//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPRD.LHD.MessageService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SW_BIN
    {
        public string ID { get; set; }
        public string LotID { get; set; }
        public Nullable<int> Code { get; set; }
        public string Defect { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<double> FailRate { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string LastOperator { get; set; }
        public Nullable<byte> RecordState { get; set; }
        public string IsPassed { get; set; }
        public Nullable<double> Limited { get; set; }
        public string IsTriggerd { get; set; }
        public Nullable<decimal> FailedBinPercent { get; set; }
    }
}
