//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPRD.LHD.SD.MailReceive
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUPS
    {
        public string GroupID { get; set; }
        public Nullable<int> Grade { get; set; }
        public string ParentGroupID { get; set; }
        public string Title { get; set; }
        public Nullable<byte> GroupType { get; set; }
        public string RelatedBUID { get; set; }
        public Nullable<byte> RecordState { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string LastOperator { get; set; }
    }
}
