//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.5472.
// 
#pragma warning disable 1591

namespace XJP.BPM.AMSService.WebService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MeetingAMSSoap", Namespace="http://tempuri.org/")]
    public partial class MeetingAMS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AMSInfomationOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MeetingAMS() {
            this.Url = global::XJP.BPM.AMSService.Properties.Settings.Default.XJP_BPM_AMSService_WebService_MeetingAMS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AMSInfomationCompletedEventHandler AMSInfomationCompleted;
        
        /// <remarks/>
        public event TestCompletedEventHandler TestCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AMSInfomation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AMSInfomation(AMSEntity entity) {
            object[] results = this.Invoke("AMSInfomation", new object[] {
                        entity});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AMSInfomationAsync(AMSEntity entity) {
            this.AMSInfomationAsync(entity, null);
        }
        
        /// <remarks/>
        public void AMSInfomationAsync(AMSEntity entity, object userState) {
            if ((this.AMSInfomationOperationCompleted == null)) {
                this.AMSInfomationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAMSInfomationOperationCompleted);
            }
            this.InvokeAsync("AMSInfomation", new object[] {
                        entity}, this.AMSInfomationOperationCompleted, userState);
        }
        
        private void OnAMSInfomationOperationCompleted(object arg) {
            if ((this.AMSInfomationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AMSInfomationCompleted(this, new AMSInfomationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Test", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Test() {
            object[] results = this.Invoke("Test", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TestAsync() {
            this.TestAsync(null);
        }
        
        /// <remarks/>
        public void TestAsync(object userState) {
            if ((this.TestOperationCompleted == null)) {
                this.TestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestOperationCompleted);
            }
            this.InvokeAsync("Test", new object[0], this.TestOperationCompleted, userState);
        }
        
        private void OnTestOperationCompleted(object arg) {
            if ((this.TestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestCompleted(this, new TestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AMSEntity {
        
        private AMSRequest[] aMSRequestField;
        
        private AMSRequestActivityFFS[] aMSRequestActivityFFSField;
        
        private AMSRequestActivityDetail[] aMSRequestActivityDetailField;
        
        private AMSSobjRequestBase[] aMSSobjRequestBaseField;
        
        /// <remarks/>
        public AMSRequest[] AMSRequest {
            get {
                return this.aMSRequestField;
            }
            set {
                this.aMSRequestField = value;
            }
        }
        
        /// <remarks/>
        public AMSRequestActivityFFS[] AMSRequestActivityFFS {
            get {
                return this.aMSRequestActivityFFSField;
            }
            set {
                this.aMSRequestActivityFFSField = value;
            }
        }
        
        /// <remarks/>
        public AMSRequestActivityDetail[] AMSRequestActivityDetail {
            get {
                return this.aMSRequestActivityDetailField;
            }
            set {
                this.aMSRequestActivityDetailField = value;
            }
        }
        
        /// <remarks/>
        public AMSSobjRequestBase[] AMSSobjRequestBase {
            get {
                return this.aMSSobjRequestBaseField;
            }
            set {
                this.aMSSobjRequestBaseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AMSRequest {
        
        private string sysIdField;
        
        private string requestIDField;
        
        private string iONumberField;
        
        private string iOSubjectField;
        
        private string iODesField;
        
        private string aMSNumberField;
        
        private string taField;
        
        private string categoryField;
        
        private string initiatedByField;
        
        private string insititutionTypeField;
        
        private string insititutionNameField;
        
        private string justifiedBusinessSelectionCriteriaField;
        
        private string statusField;
        
        private System.Nullable<System.DateTime> createTimeField;
        
        private string createdByField;
        
        private System.Nullable<System.DateTime> updateTimeField;
        
        private string updatedByField;
        
        private string latestVersionField;
        
        private string rFCActivityField;
        
        private System.DateTime syncTimeField;
        
        private bool isActiveField;
        
        private bool isHandledField;
        
        /// <remarks/>
        public string SysId {
            get {
                return this.sysIdField;
            }
            set {
                this.sysIdField = value;
            }
        }
        
        /// <remarks/>
        public string RequestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
            }
        }
        
        /// <remarks/>
        public string IONumber {
            get {
                return this.iONumberField;
            }
            set {
                this.iONumberField = value;
            }
        }
        
        /// <remarks/>
        public string IOSubject {
            get {
                return this.iOSubjectField;
            }
            set {
                this.iOSubjectField = value;
            }
        }
        
        /// <remarks/>
        public string IODes {
            get {
                return this.iODesField;
            }
            set {
                this.iODesField = value;
            }
        }
        
        /// <remarks/>
        public string AMSNumber {
            get {
                return this.aMSNumberField;
            }
            set {
                this.aMSNumberField = value;
            }
        }
        
        /// <remarks/>
        public string TA {
            get {
                return this.taField;
            }
            set {
                this.taField = value;
            }
        }
        
        /// <remarks/>
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        public string InitiatedBy {
            get {
                return this.initiatedByField;
            }
            set {
                this.initiatedByField = value;
            }
        }
        
        /// <remarks/>
        public string InsititutionType {
            get {
                return this.insititutionTypeField;
            }
            set {
                this.insititutionTypeField = value;
            }
        }
        
        /// <remarks/>
        public string InsititutionName {
            get {
                return this.insititutionNameField;
            }
            set {
                this.insititutionNameField = value;
            }
        }
        
        /// <remarks/>
        public string JustifiedBusinessSelectionCriteria {
            get {
                return this.justifiedBusinessSelectionCriteriaField;
            }
            set {
                this.justifiedBusinessSelectionCriteriaField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CreateTime {
            get {
                return this.createTimeField;
            }
            set {
                this.createTimeField = value;
            }
        }
        
        /// <remarks/>
        public string CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> UpdateTime {
            get {
                return this.updateTimeField;
            }
            set {
                this.updateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string UpdatedBy {
            get {
                return this.updatedByField;
            }
            set {
                this.updatedByField = value;
            }
        }
        
        /// <remarks/>
        public string LatestVersion {
            get {
                return this.latestVersionField;
            }
            set {
                this.latestVersionField = value;
            }
        }
        
        /// <remarks/>
        public string RFCActivity {
            get {
                return this.rFCActivityField;
            }
            set {
                this.rFCActivityField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SyncTime {
            get {
                return this.syncTimeField;
            }
            set {
                this.syncTimeField = value;
            }
        }
        
        /// <remarks/>
        public bool IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
        
        /// <remarks/>
        public bool IsHandled {
            get {
                return this.isHandledField;
            }
            set {
                this.isHandledField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AMSSobjRequestBase {
        
        private string sysIdField;
        
        private string requestSubjectField;
        
        private System.Nullable<System.DateTime> createdTimeField;
        
        private string requestStatusField;
        
        private string applicantWWIDField;
        
        private System.Nullable<bool> sMSNotificationField;
        
        private string sMSNumberField;
        
        private string departmentField;
        
        private string emailAddressField;
        
        private System.Nullable<System.DateTime> dueDateField;
        
        private string creatorWWIDField;
        
        private string processTypeField;
        
        private string objectIDField;
        
        private string supervisorWWIDField;
        
        private string creatorNameField;
        
        private string supervisorNameField;
        
        private string applicantNameField;
        
        private string applicantAdAccountField;
        
        private string applicantPhoneField;
        
        private string applicantEmailField;
        
        private string creatorAdAccountField;
        
        private string supervisorAdAccountField;
        
        private string companyCodeField;
        
        private string approvedDateField;
        
        private System.DateTime latestUpdateTimeField;
        
        private string processNameField;
        
        private string extendedField;
        
        private string applicantTitleField;
        
        private string descriptionField;
        
        private System.DateTime syncTimeField;
        
        private bool isActiveField;
        
        private bool isHandledField;
        
        /// <remarks/>
        public string SysId {
            get {
                return this.sysIdField;
            }
            set {
                this.sysIdField = value;
            }
        }
        
        /// <remarks/>
        public string RequestSubject {
            get {
                return this.requestSubjectField;
            }
            set {
                this.requestSubjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CreatedTime {
            get {
                return this.createdTimeField;
            }
            set {
                this.createdTimeField = value;
            }
        }
        
        /// <remarks/>
        public string RequestStatus {
            get {
                return this.requestStatusField;
            }
            set {
                this.requestStatusField = value;
            }
        }
        
        /// <remarks/>
        public string ApplicantWWID {
            get {
                return this.applicantWWIDField;
            }
            set {
                this.applicantWWIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> SMSNotification {
            get {
                return this.sMSNotificationField;
            }
            set {
                this.sMSNotificationField = value;
            }
        }
        
        /// <remarks/>
        public string SMSNumber {
            get {
                return this.sMSNumberField;
            }
            set {
                this.sMSNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DueDate {
            get {
                return this.dueDateField;
            }
            set {
                this.dueDateField = value;
            }
        }
        
        /// <remarks/>
        public string CreatorWWID {
            get {
                return this.creatorWWIDField;
            }
            set {
                this.creatorWWIDField = value;
            }
        }
        
        /// <remarks/>
        public string ProcessType {
            get {
                return this.processTypeField;
            }
            set {
                this.processTypeField = value;
            }
        }
        
        /// <remarks/>
        public string ObjectID {
            get {
                return this.objectIDField;
            }
            set {
                this.objectIDField = value;
            }
        }
        
        /// <remarks/>
        public string SupervisorWWID {
            get {
                return this.supervisorWWIDField;
            }
            set {
                this.supervisorWWIDField = value;
            }
        }
        
        /// <remarks/>
        public string CreatorName {
            get {
                return this.creatorNameField;
            }
            set {
                this.creatorNameField = value;
            }
        }
        
        /// <remarks/>
        public string SupervisorName {
            get {
                return this.supervisorNameField;
            }
            set {
                this.supervisorNameField = value;
            }
        }
        
        /// <remarks/>
        public string ApplicantName {
            get {
                return this.applicantNameField;
            }
            set {
                this.applicantNameField = value;
            }
        }
        
        /// <remarks/>
        public string ApplicantAdAccount {
            get {
                return this.applicantAdAccountField;
            }
            set {
                this.applicantAdAccountField = value;
            }
        }
        
        /// <remarks/>
        public string ApplicantPhone {
            get {
                return this.applicantPhoneField;
            }
            set {
                this.applicantPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string ApplicantEmail {
            get {
                return this.applicantEmailField;
            }
            set {
                this.applicantEmailField = value;
            }
        }
        
        /// <remarks/>
        public string CreatorAdAccount {
            get {
                return this.creatorAdAccountField;
            }
            set {
                this.creatorAdAccountField = value;
            }
        }
        
        /// <remarks/>
        public string SupervisorAdAccount {
            get {
                return this.supervisorAdAccountField;
            }
            set {
                this.supervisorAdAccountField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyCode {
            get {
                return this.companyCodeField;
            }
            set {
                this.companyCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ApprovedDate {
            get {
                return this.approvedDateField;
            }
            set {
                this.approvedDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LatestUpdateTime {
            get {
                return this.latestUpdateTimeField;
            }
            set {
                this.latestUpdateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string ProcessName {
            get {
                return this.processNameField;
            }
            set {
                this.processNameField = value;
            }
        }
        
        /// <remarks/>
        public string Extended {
            get {
                return this.extendedField;
            }
            set {
                this.extendedField = value;
            }
        }
        
        /// <remarks/>
        public string ApplicantTitle {
            get {
                return this.applicantTitleField;
            }
            set {
                this.applicantTitleField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SyncTime {
            get {
                return this.syncTimeField;
            }
            set {
                this.syncTimeField = value;
            }
        }
        
        /// <remarks/>
        public bool IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
        
        /// <remarks/>
        public bool IsHandled {
            get {
                return this.isHandledField;
            }
            set {
                this.isHandledField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AMSRequestActivityDetail {
        
        private string sysIdField;
        
        private string idField;
        
        private string requestIDField;
        
        private System.Nullable<bool> hasServiceProviderField;
        
        private System.Nullable<bool> productRelatedField;
        
        private string departmentAndProductField;
        
        private string gLAccountField;
        
        private string costCenterField;
        
        private string sub_AMSNumberField;
        
        private System.Nullable<System.DateTime> beginDateField;
        
        private System.Nullable<System.DateTime> endDateField;
        
        private System.Nullable<float> planning_Participant_InternalQuantityField;
        
        private System.Nullable<float> planning_Participant_ExternalQuantityField;
        
        private string planning_CountryField;
        
        private string planning_CityField;
        
        private string planning_LocationField;
        
        private string planning_DescriptionField;
        
        private System.Nullable<System.DateTime> actual_BeginDateField;
        
        private System.Nullable<System.DateTime> actual_EndDateField;
        
        private System.Nullable<float> actual_Participant_InternalQuantityField;
        
        private System.Nullable<float> actual_Participant_ExternalQuantityField;
        
        private string actual_CityField;
        
        private string actual_LocationField;
        
        private string categoryField;
        
        private System.Nullable<float> expenseSubTotalField;
        
        private System.Nullable<float> fFSSubTotalField;
        
        private System.Nullable<float> totalField;
        
        private bool defaultField;
        
        private string statusField;
        
        private System.Nullable<System.DateTime> createTimeField;
        
        private string createdByField;
        
        private System.Nullable<System.DateTime> updateTimeField;
        
        private string updatedByField;
        
        private string monitorStatusField;
        
        private string freezeStatusField;
        
        private System.DateTime syncTimeField;
        
        private bool isActiveField;
        
        private bool isHandledField;
        
        /// <remarks/>
        public string SysId {
            get {
                return this.sysIdField;
            }
            set {
                this.sysIdField = value;
            }
        }
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string RequestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> HasServiceProvider {
            get {
                return this.hasServiceProviderField;
            }
            set {
                this.hasServiceProviderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> ProductRelated {
            get {
                return this.productRelatedField;
            }
            set {
                this.productRelatedField = value;
            }
        }
        
        /// <remarks/>
        public string DepartmentAndProduct {
            get {
                return this.departmentAndProductField;
            }
            set {
                this.departmentAndProductField = value;
            }
        }
        
        /// <remarks/>
        public string GLAccount {
            get {
                return this.gLAccountField;
            }
            set {
                this.gLAccountField = value;
            }
        }
        
        /// <remarks/>
        public string CostCenter {
            get {
                return this.costCenterField;
            }
            set {
                this.costCenterField = value;
            }
        }
        
        /// <remarks/>
        public string Sub_AMSNumber {
            get {
                return this.sub_AMSNumberField;
            }
            set {
                this.sub_AMSNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> BeginDate {
            get {
                return this.beginDateField;
            }
            set {
                this.beginDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<float> Planning_Participant_InternalQuantity {
            get {
                return this.planning_Participant_InternalQuantityField;
            }
            set {
                this.planning_Participant_InternalQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<float> Planning_Participant_ExternalQuantity {
            get {
                return this.planning_Participant_ExternalQuantityField;
            }
            set {
                this.planning_Participant_ExternalQuantityField = value;
            }
        }
        
        /// <remarks/>
        public string Planning_Country {
            get {
                return this.planning_CountryField;
            }
            set {
                this.planning_CountryField = value;
            }
        }
        
        /// <remarks/>
        public string Planning_City {
            get {
                return this.planning_CityField;
            }
            set {
                this.planning_CityField = value;
            }
        }
        
        /// <remarks/>
        public string Planning_Location {
            get {
                return this.planning_LocationField;
            }
            set {
                this.planning_LocationField = value;
            }
        }
        
        /// <remarks/>
        public string Planning_Description {
            get {
                return this.planning_DescriptionField;
            }
            set {
                this.planning_DescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Actual_BeginDate {
            get {
                return this.actual_BeginDateField;
            }
            set {
                this.actual_BeginDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Actual_EndDate {
            get {
                return this.actual_EndDateField;
            }
            set {
                this.actual_EndDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<float> Actual_Participant_InternalQuantity {
            get {
                return this.actual_Participant_InternalQuantityField;
            }
            set {
                this.actual_Participant_InternalQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<float> Actual_Participant_ExternalQuantity {
            get {
                return this.actual_Participant_ExternalQuantityField;
            }
            set {
                this.actual_Participant_ExternalQuantityField = value;
            }
        }
        
        /// <remarks/>
        public string Actual_City {
            get {
                return this.actual_CityField;
            }
            set {
                this.actual_CityField = value;
            }
        }
        
        /// <remarks/>
        public string Actual_Location {
            get {
                return this.actual_LocationField;
            }
            set {
                this.actual_LocationField = value;
            }
        }
        
        /// <remarks/>
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<float> ExpenseSubTotal {
            get {
                return this.expenseSubTotalField;
            }
            set {
                this.expenseSubTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<float> FFSSubTotal {
            get {
                return this.fFSSubTotalField;
            }
            set {
                this.fFSSubTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<float> Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        public bool Default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CreateTime {
            get {
                return this.createTimeField;
            }
            set {
                this.createTimeField = value;
            }
        }
        
        /// <remarks/>
        public string CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> UpdateTime {
            get {
                return this.updateTimeField;
            }
            set {
                this.updateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string UpdatedBy {
            get {
                return this.updatedByField;
            }
            set {
                this.updatedByField = value;
            }
        }
        
        /// <remarks/>
        public string MonitorStatus {
            get {
                return this.monitorStatusField;
            }
            set {
                this.monitorStatusField = value;
            }
        }
        
        /// <remarks/>
        public string FreezeStatus {
            get {
                return this.freezeStatusField;
            }
            set {
                this.freezeStatusField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SyncTime {
            get {
                return this.syncTimeField;
            }
            set {
                this.syncTimeField = value;
            }
        }
        
        /// <remarks/>
        public bool IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
        
        /// <remarks/>
        public bool IsHandled {
            get {
                return this.isHandledField;
            }
            set {
                this.isHandledField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AMSRequestActivityFFS {
        
        private string sysIdField;
        
        private string idField;
        
        private string requestIDField;
        
        private string activity_IDField;
        
        private string categoryField;
        
        private string cVPoolIDField;
        
        private string providerNameField;
        
        private string providerBelongsField;
        
        private string providerLevelField;
        
        private string selectionCriteriaField;
        
        private System.Nullable<float> planed_ProvidingTimeField;
        
        private System.Nullable<float> planed_FeePerTimeField;
        
        private System.Nullable<float> planed_TotalField;
        
        private System.Nullable<bool> isBackUpField;
        
        private System.Nullable<float> actual_ProvidingTimeField;
        
        private System.Nullable<float> actual_FeePerTimeField;
        
        private System.Nullable<float> actual_TotalField;
        
        private string providingUnitField;
        
        private System.Nullable<bool> attendedField;
        
        private string sAPCodeField;
        
        private string currencyField;
        
        private System.Nullable<float> exchangeField;
        
        private string taxField;
        
        private System.Nullable<float> actualPaymentField;
        
        private System.Nullable<System.DateTime> createTimeField;
        
        private string createdByField;
        
        private System.Nullable<System.DateTime> updateTimeField;
        
        private string updatedByField;
        
        private string iDCardField;
        
        private System.Nullable<float> participatCountField;
        
        private System.Nullable<float> participatAmountSUMField;
        
        private System.Nullable<float> participateAmountLimitField;
        
        private System.Nullable<float> amountPercentField;
        
        private System.DateTime syncTimeField;
        
        private bool isActiveField;
        
        private bool isHandledField;
        
        /// <remarks/>
        public string SysId {
            get {
                return this.sysIdField;
            }
            set {
                this.sysIdField = value;
            }
        }
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string RequestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
            }
        }
        
        /// <remarks/>
        public string Activity_ID {
            get {
                return this.activity_IDField;
            }
            set {
                this.activity_IDField = value;
            }
        }
        
        /// <remarks/>
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        public string CVPoolID {
            get {
                return this.cVPoolIDField;
            }
            set {
                this.cVPoolIDField = value;
            }
        }
        
        /// <remarks/>
        public string ProviderName {
            get {
                return this.providerNameField;
            }
            set {
                this.providerNameField = value;
            }
        }
        
        /// <remarks/>
        public string ProviderBelongs {
            get {
                return this.providerBelongsField;
            }
            set {
                this.providerBelongsField = value;
            }
        }
        
        /// <remarks/>
        public string ProviderLevel {
            get {
                return this.providerLevelField;
            }
            set {
                this.providerLevelField = value;
            }
        }
        
        /// <remarks/>
        public string SelectionCriteria {
            get {
                return this.selectionCriteriaField;
            }
            set {
                this.selectionCriteriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<float> Planed_ProvidingTime {
            get {
                return this.planed_ProvidingTimeField;
            }
            set {
                this.planed_ProvidingTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<float> Planed_FeePerTime {
            get {
                return this.planed_FeePerTimeField;
            }
            set {
                this.planed_FeePerTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<float> Planed_Total {
            get {
                return this.planed_TotalField;
            }
            set {
                this.planed_TotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsBackUp {
            get {
                return this.isBackUpField;
            }
            set {
                this.isBackUpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<float> Actual_ProvidingTime {
            get {
                return this.actual_ProvidingTimeField;
            }
            set {
                this.actual_ProvidingTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<float> Actual_FeePerTime {
            get {
                return this.actual_FeePerTimeField;
            }
            set {
                this.actual_FeePerTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<float> Actual_Total {
            get {
                return this.actual_TotalField;
            }
            set {
                this.actual_TotalField = value;
            }
        }
        
        /// <remarks/>
        public string ProvidingUnit {
            get {
                return this.providingUnitField;
            }
            set {
                this.providingUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Attended {
            get {
                return this.attendedField;
            }
            set {
                this.attendedField = value;
            }
        }
        
        /// <remarks/>
        public string SAPCode {
            get {
                return this.sAPCodeField;
            }
            set {
                this.sAPCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<float> Exchange {
            get {
                return this.exchangeField;
            }
            set {
                this.exchangeField = value;
            }
        }
        
        /// <remarks/>
        public string Tax {
            get {
                return this.taxField;
            }
            set {
                this.taxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<float> ActualPayment {
            get {
                return this.actualPaymentField;
            }
            set {
                this.actualPaymentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CreateTime {
            get {
                return this.createTimeField;
            }
            set {
                this.createTimeField = value;
            }
        }
        
        /// <remarks/>
        public string CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> UpdateTime {
            get {
                return this.updateTimeField;
            }
            set {
                this.updateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string UpdatedBy {
            get {
                return this.updatedByField;
            }
            set {
                this.updatedByField = value;
            }
        }
        
        /// <remarks/>
        public string IDCard {
            get {
                return this.iDCardField;
            }
            set {
                this.iDCardField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<float> ParticipatCount {
            get {
                return this.participatCountField;
            }
            set {
                this.participatCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<float> ParticipatAmountSUM {
            get {
                return this.participatAmountSUMField;
            }
            set {
                this.participatAmountSUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<float> ParticipateAmountLimit {
            get {
                return this.participateAmountLimitField;
            }
            set {
                this.participateAmountLimitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<float> AmountPercent {
            get {
                return this.amountPercentField;
            }
            set {
                this.amountPercentField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SyncTime {
            get {
                return this.syncTimeField;
            }
            set {
                this.syncTimeField = value;
            }
        }
        
        /// <remarks/>
        public bool IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
        
        /// <remarks/>
        public bool IsHandled {
            get {
                return this.isHandledField;
            }
            set {
                this.isHandledField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void AMSInfomationCompletedEventHandler(object sender, AMSInfomationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AMSInfomationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AMSInfomationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void TestCompletedEventHandler(object sender, TestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591