//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMSServicesTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILES
    {
        public string FileID { get; set; }
        public string OwnerID { get; set; }
        public string ParentID { get; set; }
        public string FileType { get; set; }
        public string TokenID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string OriginalFileName { get; set; }
        public string ExtendFileName { get; set; }
        public string Title { get; set; }
        public string Keyword { get; set; }
        public string Memo { get; set; }
        public string StorageAbsoluteFileName { get; set; }
        public string StoreAbsolutePath { get; set; }
        public string StoreRelativePath { get; set; }
        public string PDFAbsoluteFileName { get; set; }
        public string PDFAbsolutePath { get; set; }
        public string PDFRelativePath { get; set; }
        public Nullable<bool> ConvertToPDFSuccessed { get; set; }
        public string Tag { get; set; }
        public string FileState { get; set; }
        public Nullable<long> FileSize { get; set; }
        public string ClientIP { get; set; }
        public string ContentType { get; set; }
        public string UploaderID { get; set; }
        public string RelativeProjectNames { get; set; }
        public string RelativeUserNames { get; set; }
        public string Thumbnail { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string QuickID { get; set; }
        public string CategoryQueryIDs { get; set; }
        public Nullable<byte> PayLevel { get; set; }
        public Nullable<byte> SecretLevel { get; set; }
        public string LargeThumbnail { get; set; }
        public Nullable<bool> DisplayInNotifications { get; set; }
        public Nullable<bool> PublicReview { get; set; }
        public Nullable<bool> PublicDownload { get; set; }
        public Nullable<bool> PreviewAfterPermit { get; set; }
        public Nullable<bool> DownloadAfterPermit { get; set; }
        public Nullable<int> DownloadTimes { get; set; }
        public Nullable<int> OpenedTimes { get; set; }
        public Nullable<int> ReadCount { get; set; }
        public string OwnerName { get; set; }
    }
}
